// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
using DataMeshGroup.Fusion.Model;
using DataMeshGroup.Fusion.Util;
using ProfanityFilter;
using QRCoder;

namespace DataMeshGroup.Fusion.Pairing.WinForms
{
    public partial class PairingDialog : Form
    {
        public string SaleID { get; set; }
        public string POIID { get; set; }
        public string KEK { get; set; }

        string posName;
        PairingData pairingData;
        FusionClient fusionClient;

        public enum DialogType { Normal, Success, Error };
        bool pairingSuccessful;
        bool manualEntry;

        int nextTimerCount;


        public PairingDialog(FusionClient fusionClient, string posName)
        {
            InitializeComponent();

            if (fusionClient is null)
            {
                throw new ArgumentNullException(nameof(fusionClient));
            }
            if (fusionClient.LoginRequest?.SaleSoftware?.CertificationCode is null)
            {
                throw new ArgumentNullException("CertificationCode");
            }
            this.pairingSuccessful = false;
            this.manualEntry = false;
            this.fusionClient = fusionClient;
            this.posName = (new ProfanityFilter.ProfanityFilter()).CensorString(posName);

            PnlManualEntry.Visible = false;
            PnlQRCode.Visible = true;
            PnlPairingStatus.Visible = false;
        }

        private void PairingDialog_Load(object sender, EventArgs e)
        {
            UpdateQRCode();
            ResetNextTimer();
        }


        private static void SetLabel(Label label, string content)
        {
            label.Text = content;
            label.Visible = !string.IsNullOrEmpty(content);
        }

        public void ShowPairingLogonStatus(string title, string displayLine1, string displayText, DialogType dialogType, bool enableOk, bool enableNext)
        {
            //// Set title
            Color foreground, background;
            SetLabel(LblPaymentDialogTitle, title);

            switch (dialogType)
            {
                case DialogType.Error:
                    background = System.Drawing.ColorTranslator.FromHtml("#A20025"); //red
                    foreground = Color.White;
                    break;
                case DialogType.Success:
                    background = System.Drawing.ColorTranslator.FromHtml("#008A00"); // green
                    foreground = Color.White;
                    break;
                case DialogType.Normal:
                default:
                    background = System.Drawing.ColorTranslator.FromHtml("#F0F0F0");
                    foreground = Color.Black;
                    break;
            }
            LblPaymentDialogTitle.BackColor = background;
            LblPaymentDialogTitle.ForeColor = foreground;

            SetLabel(LblPaymentDialogLine1, displayLine1);
            SetLabel(TxtPaymentDialogText, displayText);

            BusyIndicator.Visible = !enableOk;

            BtnDialogOK.Visible = enableOk;
            BtnNext.Visible = enableNext;

            if (enableOk)
            {
                BtnDialogOK.Focus();
            }
            if (enableNext)
            {
                BtnNext.Focus();
            }


            if (this.Visible)
            {
                this.Show();
            }

            // Ensure the dialog is centered on the desktop
            if (Screen.PrimaryScreen?.WorkingArea != null)
            {
                Rectangle r = Screen.PrimaryScreen.WorkingArea;
                this.Location = new Point((r.Width - this.Width) / 2, (r.Height - this.Height) / 2);
            }

            PnlManualEntry.Visible = false;
            PnlQRCode.Visible = false;
            PnlPairingStatus.Visible = true;
        }


        private async void BtnNext_Click(object sender, EventArgs e)
        {
            await DoPairingLogon();
        }

        private void BtnEnterCredentialsManually_Click(object sender, EventArgs e)
        {
            PnlManualEntry.Visible = true;
            PnlQRCode.Visible = false;
            PnlPairingStatus.Visible = false;
            manualEntry = true;
        }

        private void BtnDialogOk_Click(object sender, EventArgs e)
        {
            DialogResult = pairingSuccessful ? DialogResult.OK : DialogResult.Cancel;
        }


        private void UpdateQRCode()
        {
            pairingData = fusionClient.GetPairingData(posName);
            string pairingDataString = Newtonsoft.Json.JsonConvert.SerializeObject(pairingData);

            QRCodeGenerator qrGenerator = new QRCodeGenerator();
            QRCodeData qrCodeData = qrGenerator.CreateQrCode(pairingDataString, QRCodeGenerator.ECCLevel.M);
            QRCode qrCode = new QRCode(qrCodeData);
            qrPictureBox.Image = qrCode.GetGraphic(pixelsPerModule: 4);
        }

        private void ResetNextTimer()
        {
            BtnNext.Enabled = false;

            NextTimer.Enabled = false;
            nextTimerCount = 9;
            NextTimer.Interval = 1000;
            NextTimer.Enabled = true;

            lblNextTimer.Text = $" {nextTimerCount}";
            lblNextTimer.Visible = true;
        }

        private void NextTimer_Tick(object sender, EventArgs e)
        {
            if (nextTimerCount == 1)
            {
                // end timer
                lblNextTimer.Visible = false;
                NextTimer.Enabled = false;
                BtnNext.Enabled = true;
            }
            else
            {
                nextTimerCount--;
                lblNextTimer.Text = $"{nextTimerCount}";
            }
        }


        private async Task DoPairingLogon()
        {


            // Record existing details
            string previousSaleID = fusionClient.SaleID;
            string previousPOIID = fusionClient.POIID;
            string previousKEK = fusionClient.KEK;

            try
            {
                ShowPairingLogonStatus("PAIRING WITH TERMINAL", "", "", DialogType.Normal, false, false);

                // Attempt a login with the new credentials
                if (manualEntry)
                {
                    fusionClient.SaleID = txtSaleID.Text;
                    fusionClient.POIID = txtPOIId.Text;
                    fusionClient.KEK = txtKEK.Text;
                    fusionClient.LoginRequest.Pairing = null;
                }
                else
                {
                    fusionClient.SaleID = pairingData.SaleID;
                    fusionClient.POIID = pairingData.PairingPOIID;
                    fusionClient.KEK = pairingData.KEK;
                    fusionClient.LoginRequest.Pairing = true;
                }


                // Attempt pairing login 
                var result = await fusionClient.SendRecvAsync<LoginResponse>(fusionClient.LoginRequest, new CancellationTokenSource(TimeSpan.FromSeconds(10)).Token);
                if (!result.Response.Success)
                {
                    // Roll back to old credentials
                    fusionClient.SaleID = previousSaleID;
                    fusionClient.POIID = previousPOIID;
                    fusionClient.KEK = previousKEK;
                    ShowPairingLogonStatus("PAIRING UNSUCCESSFUL", ErrorConditionToDisplayText(result.Response?.ErrorCondition), result.Response?.AdditionalResponse, DialogType.Error, true, false);
                    return;
                }

                // Make credentials available for the caller
                fusionClient.LoginRequest.Pairing = null;
                fusionClient.POIID = fusionClient.LastSaleToPOIResponse.MessageHeader.POIID;
                SaleID = fusionClient.SaleID;
                POIID = fusionClient.POIID;
                KEK = fusionClient.KEK;

                // Attempt a login using the returned credentials
                if (!manualEntry)
                {
                    result = await fusionClient.SendRecvAsync<LoginResponse>(fusionClient.LoginRequest, new CancellationTokenSource(TimeSpan.FromSeconds(10)).Token);
                    if (!result.Response.Success)
                    {
                        // Roll back to old credentials
                        fusionClient.SaleID = previousSaleID;
                        fusionClient.POIID = previousPOIID;
                        fusionClient.KEK = previousKEK;
                        ShowPairingLogonStatus("PAIRING UNSUCCESSFUL", ErrorConditionToDisplayText(result.Response?.ErrorCondition), result.Response?.AdditionalResponse, DialogType.Error, true, false);
                        return;
                    }
                }

                ShowPairingLogonStatus("PAIRING SUCCESSFUL", "", "", DialogType.Success, true, false);
                pairingSuccessful = true;
            }
            catch (Exception ex)
            {
                // Roll back to old credentials
                fusionClient.SaleID = previousSaleID;
                fusionClient.POIID = previousPOIID;
                fusionClient.KEK = previousKEK;
                ShowPairingLogonStatus("PAIRING  ", "", ex.Message, DialogType.Error, true, false);
            }
        }

        private void BtnBack_Click(object sender, EventArgs e)
        {
            PnlManualEntry.Visible = false;
            PnlQRCode.Visible = true;
            PnlPairingStatus.Visible = false;
            manualEntry = false;
        }


        public static string ErrorConditionToDisplayText(ErrorCondition? errorCondition)
        {
            switch (errorCondition)
            {
                case ErrorCondition.Aborted:
                    return "ABORTED";
                case ErrorCondition.Busy:
                    return "BUSY";
                case ErrorCondition.Cancel:
                    return "CANCEL";
                case ErrorCondition.DeviceOut:
                    return "DEVICE OUT";
                case ErrorCondition.InProgress:
                    return "IN PROGRESS";
                case ErrorCondition.InsertedCard:
                    return "INSERTED CARD";
                case ErrorCondition.InvalidCard:
                    return "INVALID CARD";
                case ErrorCondition.LoggedOut:
                    return "LOGGED OUT";
                case ErrorCondition.MessageFormat:
                    return "MESSAGE FORMAT";
                case ErrorCondition.NotAllowed:
                    return "NOT ALLOWED";
                case ErrorCondition.NotFound:
                    return "NOT FOUND";
                case ErrorCondition.PaymentRestriction:
                    return "PAYMENT RESTRICTION";
                case ErrorCondition.Refusal:
                    return "REFUSAL";
                case ErrorCondition.UnavailableDevice:
                    return "UNAVAILABLE DEVICE";
                case ErrorCondition.UnavailableService:
                    return "UNAVAILABLE SERVICE";
                case ErrorCondition.Unknown:
                    return "UNKNOWN";
                case ErrorCondition.UnreachableHost:
                    return "UNREACHABLE HOST";
                case ErrorCondition.WrongPIN:
                    return "WRONG PIN";
                case null:
                    return "UNKNOWN";
                default:
                    return errorCondition.Value.ToString();
            }

        }

        private void lblVersion_Click(object sender, EventArgs e)
        {

        }
    }


}
